export enum RolesEnum {
    FOPS_ADMINISTRADORTECNICO=5,
    FOPS_CUSTOMER_B2C = 6,
    FOPS_EJECUTIVODEVENTAS=7,
    FOPS_COORDINADOR=8,
    FOPS_DISENADOR=9,
    FOPS_OPERADORDEPISO=18,
    FOPS_BOCETISTA=19 
}
export enum identificationdataFOPS_COORDINADOR{
    Item_code = 'false',
}