export class TechnicalDataLines {

    public static GetTechnicalDataLineg = {
        heattranferRollo: 52,
        tejidoOrilloCortado: 60,
        estampados: 66,
        flexoPapelTextil: 74,
        flexoPapelNoTextil: 76,
        heatTranferPiezas: 56,
        heatTransferLaser: 84,
        thermal: 68,
        reatasyPretinas: 64,
        mascarillasTejidas: 67,
        estampaciónSublimacion: 78,
        sinteticaScreen: 79,
        sintetico: 0,
        estampadoScreen: 83,
        troquelado: 81,
        sinteticoOtros: 82,
        kitOffset: 86,
        kitEstampadoSublimacion: 88,
        kitOrilloMexico: 89,
        cortado: 0,
        kitHeattransfer: 87,
        kitFlexoMexico: 91,
        mezclasyTintas: 30,
        offSet: 77,
        telas: 63,
    }
}
