export interface SampleDataDto {
    companyId: number;
    sampleId: number;
    formNumber: number;
    purchaseNumber: string;
    plantId: number;
    customerId: number;
    storeHouseId: number | null;
    productId: string;
    sampleQuantity: number | null;
    placementDate: string | null;
    sampleDate: string;
    requestDate: string;
    promisedDate: string | null;
    sampleModifiedDate: string | null;
    completedDate: string | null;
    approvedDate: string | null;
    billingAddress: number | null;
    shippingAddress: number | null;
    carrierId: number | null;
    customerCarrierAccount: string;
    repetitionApprovedDate: string | null;
    repetitionOrderNumber: number | null;
    repetitionOrderItem: number | null;
    sampleApprovalTypeId: number;
    processTypeId: number | null;
    samplePendingToPrint: string;
    sampleLastShipmentDate: string | null;
    sampleLastReceptioDate: string | null;
    sampleShipmentsNumber: number | null;
    samplesNotes: string;
    fulfilledManual: string;
    fulfilledBy: string;
    sampleRejectionId: number;
    sampleStatusId: number | null;
    sampleImageUrl: string;
    createdByUser: string;
    creationDate: string;
    modifiedByUser: string;
    modifiedDate: string;
}